name: csound_wasm
on:
  push:
    branches:
      - feature/webaudio-csound
jobs:
  csound-wasm:
    env:
      wasm_bin_dir: ./wasm
    name: Compiling wasm bins
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: csound
        authToken: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjJDIzMTgiLCJqdGkiOiJhNDQzZmMwMi1mMDBjLTQzNDUtYjA3YS1jYzJjYjIzYjE2OTAiLCJzY29wZXMiOiJjYWNoZSJ9.UOQEV1Hd1ZEQdNF1STxbt0wcCrIrihsv4KThD_wHk3E'
    - name: Compile wasm binaries
      run: cd $wasm_bin_dir && bash compile.sh
    - name: Zip the compilation output
      run: |
          cd $wasm_bin_dir
          nix-env -f '<nixpkgs>' -iA zip
          zip -r lib.zip lib
    - name: Archive Wasm Artifacts
      uses: actions/upload-artifact@master
      with:
        name: lib
        path: ${{ env.wasm_bin_dir }}/lib.zip
  browser-test:
    env:
      wasm_bin_dir: ./wasm
      wasm_browser_dir: ./wasm/browser
    name: Browser bundle build and test
    needs: csound-wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: csound
          authToken: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjJDIzMTgiLCJqdGkiOiJhNDQzZmMwMi1mMDBjLTQzNDUtYjA3YS1jYzJjYjIzYjE2OTAiLCJzY29wZXMiOiJjYWNoZSJ9.UOQEV1Hd1ZEQdNF1STxbt0wcCrIrihsv4KThD_wHk3E'
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: lib
      - name: Uncompress freshly compiled wasm artifacts
        run: |
          nix-env -f '<nixpkgs>' -iA unzip
          unzip ./lib.zip -d $wasm_bin_dir
      - name: Build the production js module bundle
        run: |
          cd $wasm_browser_dir
          yarn
          yarn build:prod
      - name: Install test dependencies
        run: |
          cd $wasm_browser_dir
          export NIXPKGS_ALLOW_UNFREE=1
          nix-shell --run 'exit 0'
      - name: Run the unit-tests
        run : |
          export NIXPKGS_ALLOW_UNFREE=1
          cd $wasm_browser_dir
          nix-shell --pure
          yarn test:ci
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: ${{ env.wasm_browser_dir }}/tests/*.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
