name: csound_wasm
on:
  push:
    branches:
      - feature/webaudio-csound
jobs:
  csound-wasm:
    env:
      wasm_bin_dir: ./wasm
      wasm_browser_dir: ./wasm/browser
    name: csound-wasm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: csound
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Compile wasm binaries
      run: cd $wasm_bin_dir && bash compile.sh
